title = "The Town's Well"
name = "jacobsky-blog"
description = "My personal homepage."
homepage = "https://jacobsky.github.io"

# The URL the site will be built for
base_url = "https://jacobsky.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The theme stuff.
theme = "zerm"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
logo_text = "The Town's Well"
# Put all your custom variables here
# ["orange", "blue", "red", "green", "pink"]
theme_color = "blue"
author = "jacobsky"
show_author = false
show_tags = false
show_categories = false
# Menu items to display. You define a url and the name of the menu item.
# NOTE: `$BASE_URL/` must be included in the url name.
main_menu = [
    {url="/articles/", name="Articles"},
    {url="/ramblings/", name="Ramblings"},
    {url="/projects/", name="Projects"},
]


# center theme with default width.
center = true